---
language: "python"
python:
  - "3.6"

# Install required Python packages.
install:
  - "pip install -r requirements.txt"

# Perform pre-checks
before_script:
  - "make lint"

# Perform runbook testing with mock ASA inputs.
script:
  - "make run"
...
