---
language: "python"
python:
  - "3.6"

# Install required Python packages.
install:
  - "pip install -r requirements.txt"

# Perform pre-checks before gameplay simulations.
before_script:
  - "make lint"
  - "make db"

# Perform gameplay simulation with various inputs.
script:
  - "make run"
...
